# Generated by Django 3.0 on 2019-12-15 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_auto_20191215_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='/static/avatar/default_avatar.jpg', upload_to='static/avatar/'),
        ),
    ]
