# Generated by Django 3.0 on 2019-12-15 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_auto_20191215_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='upload/avatar/default_avatar.jpg', upload_to='upload/avatar/', verbose_name='头像'),
        ),
    ]
