# Generated by Django 3.0 on 2019-12-21 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0016_auto_20191221_0846'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('clazz', models.CharField(max_length=32)),
                ('sort', models.IntegerField(default=0)),
                ('desc', models.CharField(max_length=255, null=True)),
                ('deleted', models.IntegerField(default=0)),
                ('maximum_users', models.IntegerField(null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(null=True)),
                ('create_user', models.IntegerField(default='0')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system.Organization')),
            ],
        )
    ]
