# Generated by Django 3.0 on 2019-12-21 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0017_auto_20191221_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='user', to='system.Organization'),
            preserve_default=False,
        ),
    ]
