# Generated by Django 3.0 on 2019-12-21 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0019_auto_20191221_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='clazz',
        ),
        migrations.AlterModelTable(
            name='organization',
            table='sys_organization',
        ),
        migrations.AlterModelTable(
            name='user',
            table='sys_user',
        ),
    ]
