# Generated by Django 3.0 on 2019-12-21 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0021_auto_20191221_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='desc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='maximum_users',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
