# Generated by Django 3.0 on 2019-12-23 01:34

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0023_auto_20191221_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='sort',
        ),
        migrations.AlterField(
            model_name='organization',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='system.Organization'),
        ),
        migrations.AlterModelTable(
            name='organization',
            table=None,
        ),
    ]
