# Generated by Django 3.0 on 2019-12-23 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0024_auto_20191223_0934'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='organization',
            table='sys_organization',
        ),
    ]
