# Generated by Django 3.0 on 2019-12-23 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0025_auto_20191223_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='create_user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='create_user',
        ),
        migrations.AddField(
            model_name='organization',
            name='sort',
            field=models.IntegerField(default=0),
        ),
    ]
