# Generated by Django 3.0 on 2019-12-23 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0026_auto_20191223_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='sort',
        ),
    ]
